#!/usr/bin/env python3
"""
BGM埋め込みスクリプト
- assets/audio/ の mp3 を base64 化して js/gen/audio.js (自動生成ファイル) に書き出す

使い方:
  python3 tools/build_audio.py
依存: なし(標準ライブラリのみ)
"""
import base64, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

# BGM_SRC のキー名 → mp3 ファイル。エンジン側は BGM_SRC.TITLE などで参照する
FILES = {
    'TITLE': 'assets/audio/bgm_title.mp3',   # タイトル〜チュートリアル
    'STAGE': 'assets/audio/bgm_stage.mp3',   # 道中
    'BOSS':  'assets/audio/bgm_boss.mp3',    # ボス戦(みその/オタサーの姫 共通)
}

def main():
    out = ['// AUTO-GENERATED by tools/build_audio.py — 手で編集しないこと',
           '"use strict";',
           'const BGM_SRC = {']
    for name, relpath in FILES.items():
        data = (ROOT / relpath).read_bytes()
        b64 = base64.b64encode(data).decode()
        out.append(f'{name}: "data:audio/mpeg;base64,{b64}",')
        print(f'injected {name} ({len(b64)} chars from {relpath}, {len(data)} bytes)')
    out += ['};', '']
    (ROOT / 'js' / 'gen' / 'audio.js').write_text('\n'.join(out), encoding='utf-8')
    print('js/gen/audio.js updated')

if __name__ == '__main__':
    main()
